version: "3.8"

services: 
  ninja-backend:
    build:
      context : .
      dockerfile: Dockerfile.backend
    image: ninja-backend:0.0.1
    container_name: ninja-backend
    volumes: 
      - ${BACKEND_PATH}:/app
    ports: 
      - "${BACKEND_PORT}:5000"
    command: bash -c "npm run dev"
    logging:
      options:
        max-size: 3m
    depends_on:
      - ninja-db

  ninja-frontend:
    build:
      context : .
      dockerfile: Dockerfile.frontend
    image: ninja-frontend:0.0.1
    container_name: ninja-frontend
    volumes: 
      - ${FRONTEND_PATH}:/app
    ports: 
      - "${FRONTEND_PORT}:5000"
    command: bash -c "ng serve --port 5000 --host 0.0.0.0"
    logging:
      options:
        max-size: 3m
    depends_on:
      - ninja-backend
    # tty: true

  ninja-db:
    container_name: ninja-db
    image: mysql:5.7.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_PATH}:/var/lib/mysql

  ninja-adminer:
    image: adminer:4.8.0
    container_name: ninja-adminer
    environment:
      ADMINER_DEFAULT_SERVER: ninja-db
    restart: always
    ports:
      - ${ADMINER_PORT}:8080